# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: Checkbox List
  description: A list of checkboxes for selecting multiple items
  icon: checklist
  tags: ["form", "input"]

# Defines the structure of this component, as well as the default values
blueprint:
  name: ""
  label: ""
  checkboxes:
  other: false
  minchecked: 0
  maxchecked: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name:
    type: text
    comment: >-
      Unique name submitted with the value of the field.
      Must start with a letter, numbers and the symbols "-","_",":","." are allowed.
  label:
    type: text
  checkboxes:
    type: array
  checkboxes[*]:
    type: text
  other:
    type: checkbox
    comment: Add text input "Other" field
  minchecked:
    type: number
    label: Minimum Checked
    comment: Minimum number of checked boxes in submitted list. Set to 0 to disable.
    options:
      step: 1
      min: 0
  maxchecked:
    type: number
    label: Maximum Checked
    comment: Maximum number of checked boxes in submitted list. Set to 0 to disable.
    options:
      step: 1
      min: 0
