# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Files
  description: Display files to download.
  icon: file_present
  tags: ["file", "collection"]
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - content
        - classes
        - height
        - indent
        - align
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
        - background_fit
  preview:
    subtext:
      - template: "{files[*].title|default=files[*].url}"
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  files:
    - path:
      title:
      description:
  show_filesize: true
  show_filetype: true
  content:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  background_fit:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
  description:
    type: markdown
