# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: Date/Time
  description: Select a date, time or both.
  icon: edit_calendar
  tags: ["form", "input"]

# Defines the structure of this component, as well as the default values
blueprint:
  name: ""
  label: ""
  type: datetime
  required: false
  # mindate: 0
  # maxdate: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name:
    type: text
    comment: >-
      Unique name submitted with the value of the field.
      Must start with a letter, numbers and the symbols "-","_",":","." are allowed.
  label:
    type: text
  type:
    type: select
    options:
      values:
        - date
        - time
        - datetime
  required:
    type: checkbox
    comment: Require this field to be filled to submit.
  # mindate:
  #   type: datetime
  #   label: Minimum Date
  #   comment: Minimum number of checked boxes in submitted list. Set to 0 to disable.
  #   options:
  #     step: 1
  #     min: 0
  # maxchecked:
  #   type: datetime
  #   label: Maximum Date
  #   comment: Maximum number of checked boxes in submitted list. Set to 0 to disable.
  #   options:
  #     step: 1
  #     min: 0
