# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: Group
  description: Group input fields
  icon: view_agenda
  tags: ["form", "layout"]

# Defines the structure of this component, as well as the default values
blueprint:
  legend: ""
  form_blocks: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  legend:
    type: text
    comment: The label describing the field group
