# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - slider_blocks
  label: Columns
  description: Layout content in columns.
  icon: view_column
  tags: []
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - content
        - classes
        - height
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
        - background_fit
  preview:
    subtext:
      - template: "{content_blocks[*]._bookshop_name}"
    image:
      - key: background_image
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  content_blocks: []
  collapse: true
  fullwidth: false
  layout: [1]
  content:
  classes:
  height:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  background_fit:

_inputs:
  content_blocks:
    type: array
    options:
      structure: _structures.content_blocks
  collapse:
    type: checkbox
    comment: Restrict to one column at small screen sizes
  fullwidth:
    type: checkbox
    label: Full Width
    comment: Allow column items to fill the full width of the page
  layout:
    type: array
    comment: Set a fixed number of columns per row. The last row will be repeated in case of extra items.
  layout[*]:
    type: range
    options:
      min: 1
      step: 1
      max: 6
  classes:
  label: Style
  type: multiselect
  options:
    allow_create: true
    values:
      - no-indent
      - no-indent-top
      - no-indent-bottom
      - no-indent-left
      - no-indent-right
