# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: Select
  description: Drop-down choice menu
  icon: baseline-list-alt
  tags: ["form", "input"]

# Defines the structure of this component, as well as the default values
blueprint:
  name: ""
  label: ""
  options:
  required:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name:
    type: text
    comment: >-
      Unique name submitted with the value of the field.
      Must start with a letter, numbers and the symbols "-","_",":","." are allowed.
  label:
    type: text
  options:
    type: multiselect
    comment: The choices available in the dropdown.
    options:
      allow_create: true
  required:
    type: checkbox
    comment: Require this field to be filled to submit.
