# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Breadcrumbs
  description: Navigate to ancestors of this page
  icon: signpost
  tags: ["navigation"]
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - content
        - classes
        - height
        - indent
        - align
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
        - background_fit
  preview:
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  showHome:
  homeIcon:
  separator:
  justify:
  content:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  background_fit:

_inputs:
  showHome:
    type: choice
    label: Show Home
    options:
      values:
        - "none"
        - "label"
        - "icon"
        - "both"
  homeIcon:
    type: text
    label: Home Icon
    options:
      pattern: "^(.*:.*)?$"
      pattern_message: "Must be the name of an icon from an installed @iconify-json icon set."
  separator:
    type: text
    description: Icon to use as a seperator between items. Optionally use a single letter to display as the seperator e.g. "/"
    options:
      pattern: "^(.?|.*:.*)$"
      pattern_message: "Must be either a single character, or the name of an icon from an installed @iconify-json icon set."
  justify:
    type: choice
    options:
      values:
        - "left"
        - "center"
        - "right"
      allow_create: false
      allow_empty: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
