# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Form
  description: Customisable Web Form
  icon: contact_support
  tags: ["form", "input"]

# Defines the structure of this component, as well as the default values
blueprint:
  name: ""
  action: ""
  form_blocks: []
  background_color:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name:
    type: text
    comment: >-
      Unique form name, should be different than all field names.
      Must start with a letter, numbers and the symbols "-","_",":","." are allowed.
  action:
    type: url
    comment: The URL the form will be submitted to.
