# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: Info text
  description: Add extra information inside the form
  icon: info
  tags: ["form"]

# Defines the structure of this component, as well as the default values
blueprint:
  content:
  style: Default

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content:
    type: markdown

_select_data:
  styles:
    - Default
    - Info
    - Warning
    - Details
