# Metadata about this component, to be used in the CMS
spec:
  structures:
    - card-index
  label: Card
  description: A customisable card
  icon: web_stories
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  include: ["title", "link"]
  layout: vertical

_inputs:
  include:
    type: multiselect
    options:
      allow_create: true
      allow_empty: false
      values: ["title", "description", "thumbnail", "link", "read-more"]
  layout:
    type: choice
    options:
      allow_empty: false
      values: ["vertical", "horizontal"]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
