spec:
  structures:
    - content_blocks
  label: Slider
  description: Rotating Carousel
  icon: view_column
  tags: []

blueprint:
  slides:
    - content:
      background_color:
      background_image:
  height: 50
  autoplay: 0
  perView: 1
  focusAtCenter: true
  focusAt: 0
  showBullets: true
  showArrows: true
  indent: false
  transition: Slider
  transitionDuration: 0.4

_inputs:
  content:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: src/styles/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true
  height:
    type: number
    comment: Slider height, in percentage of browser window height (vh).
    options:
      min: 0
      max: 100
  autoplay:
    type: number
    comment: Time between automatically switching slides in seconds. (0 to disable autoplay.)
    options:
      min: 0
  perView:
    type: number
    label: Slides Per View
    comment: Number of slides visible at once.
    options:
      min: 1
      step: 1
  focusAtCenter:
    label: Focus Centre Slide
    comment: The central visible slide is treated as the active slide. Best when slides per view is odd and bigger than 1.
  focusAt:
    label: Focus at Slide
    comment: The nth visible slide is treated as the active slide. Mainly useful when slides per view is bigger than 1. (Leftmost visible slide is slide 0)
    hidden: focusAtCenter
    type: number
    options:
      min: 0
      step: 1
  transition:
    type: select
    comment: >
      Slider rewinds the slider to the start after last slide, 
      Carousel continues in the same direction with the starting items added after the end. 
      Fader does not slide and instead slowly fades between items (Fader overwrites some options).
    options:
      values:
        - Slider
        - Carousel
        - Fader
  transitionDuration:
    type: number
    comment: Time spent animating between slides in seconds.
    options:
      min: 0
      step: 0.1
      max: 10
