spec:
  structures:
    - content_blocks
  label: Slider
  description: Rotating Carousel
  icon: view_column
  tags: []

blueprint:
  slides:
    - content:
      background_colour:
      background_image:

_inputs:
  slides:
    content:
      type: markdown
