# Metadata about this component, to be used in the CMS
spec:
  structures:
    - secondary_navigation
  label: Quicklink
  description: Add a link to the secondary navigation
  icon: add_link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text:
  link:
  new_tab: false
  order:

_inputs:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
