# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery
  description: Display images in a gallery.
  icon: collections
  tags: ["image", "collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  height:
  columns: 0
  indent: true
  images:
    - image:
      title:
      description:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  height:
    type: range
    options:
      step: 1
      max: 100
      min: 0
  columns:
    type: number
    comment: Set the number of columns. 0 puts all images in one row.
    options:
      step: 1
      min: 0
  indent:
    type: switch
  images:
    icon: image
  title:
    type: text
  description:
    type: markdown
