# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery
  description: Display images in a gallery.
  icon: "gallery_thumbnail"
  tags: ["image", "collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  images:
    - image:
        file: /images/hero/espresso.jpg
        title: Title
        description: Description

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
