# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery
  description: Display images in a gallery.
  icon: collections
  tags: ["image", "collection"]
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - content
        - classes
        - height
        - indent
        - align
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
        - background_fit
  preview:
    image:
      - key: image[0].image
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  columns: 0
  gap: true
  aspect: 1
  linkgallery: false
  lightbox: true
  placeholder: true
  images:
    - image:
      title:
      description:
      alt:
      link:
  content:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  background_fit:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  columns:
    type: number
    comment: Set the number of columns. 0 puts all images in one row.
    options:
      step: 1
      min: 0
  aspect:
    type: range
    options:
      step: 0.1
      max: 2
      min: 0.5
  images:
    icon: image
  title:
    type: text
  description:
    type: markdown
  lightbox:
    type: checkbox
    hidden: linkgallery
  linkgallery:
    type: checkbox
    label: Link Gallery
    comment: Clicking gallery items redirects the user to their respective links
