# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Map
  description: Embed a map element
  icon: public
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  lat: -32.0390536
  lng: 115.631223
  zoom: 12
  height: 

_inputs:
  lat:
    label: Latitude
    comment: Latitude and Longitude can be copied by right clicking a position on the map in Google Maps. 
    type: number
  lng:
    label: Longitude
    type: number
  zoom:
    type: slider
    label: Zoom
    comment: "1: World, 5: Continent, 10: City, 15: Streets, 20: Buildings"
    comment: 
    options:
      min: 0
      max: 18
      step: 0.25
  height:
    type: number
    comment: Map height, in percentage of browser window height (vh).
    options:
      min: 0
      max: 100

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
# _inputs:
#   description:
#     type: markdown
