# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Card Index
  description: List information about other pages
  icon: recent_actors
  tags: []

blueprint:
  target: ""
  include: []

preview:
  target: /
  include: ["title", "thumbnail", "description", "link"]
