# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Card Index
  description: List information about other pages
  icon: recent_actors
  tags: []
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - content
        - classes
        - height
        - indent
        - align
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
        - background_fit
  preview:
    subtext:
      - key: target
    image:
      - key: background_image
    metadata:
      - text:
          - key: classes
        icon: tag

blueprint:
  target: ""
  collection:
  card:
    _bookshop_name: card-index/cards/card
    include: ["title", "link"]
    layout: "vertical"
  filters: []
  prefilter: []
  columns: 4
  pageSize: 0
  limit: 0
  content:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  background_fit:

preview:
  target: /
  card:
    - _bookshop_name: card-index/cards/card
      include: ["title", "link"]
      layout: "vertical"

_inputs:
  target:
    type: text
    label: Target
    comment: Path to fetch cards from.
    options:
      empty_type: string
  card:
    type: object
    options:
      structures: _structures.card_index
  filters:
    type: multiselect
    label: User Filters
    comment: Show user-selectable filters for certain properties
    options:
      values:
        - categories
      allow_create: true
      empty_type: array
  prefilter:
    type: array
    label: Prefilter
    comment: Filter which cards will be displayed.
    context:
      open: false
      title: Filter Formatting
      icon: help
      content: >-
        Filters can be defined in the following formats:

         * `property~=value` (property contains value)

         * `property=value` (property is exactly value)

         * `property` (card has a property)

        Cards that match one of the filters will be displayed.

        E.g. `categories~=Blog` `categories~=News` will only display posts in the categories Blog or News.
  prefilter[*]:
    type: text
  columns:
    type: number
    label: Columns
    comment: The number of columns items are arranged into, provided there is space.
    options:
      min: 1
      step: 1
      max: 8
  pageSize:
    type: number
    label: Page Size
    comment: How many items to show per page. 0 disables pagination and shows all items at once.
    options:
      min: 0
      step: 1
  limit:
    type: number
    label: Limit Cards
    comment: How many items to show in total. 0 disables the limit.
    options:
      min: 0
      step: 1
