# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Video Player
  description: Embed a video player
  icon: movie
  tags: ["video"]
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - content
        - classes
        - height
        - indent
        - align
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
  preview:
    text: Video Player
    subtext:
      - key: src
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  src:
  content:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
