# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Video Player
  description: Embed a video player
  icon: movie
  tags: []
  preview:
    text: Video Player
    subtext:
      - key: src
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  src:
  content:
  classes:
