# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Map
  description: Embed a map element
  icon: public
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  location:
  lat: -32.0390536
  lng: 115.631223
  zoom: 12
  mapType: roadmap
  # marker: false
  height: 40
  indent: true
  # mapId:
  # style:

_inputs:
  location:
    label: Location
    comment: Place name, address, or plus code. Displays a marker if set.
  lat:
    label: Latitude
    comment: Required if location is not specified. Latitude and Longitude can be copied by right clicking a position on the map in Google Maps.
    type: number
  lng:
    label: Longitude
    type: number
  zoom:
    type: range
    label: Zoom
    comment: "1: World, 5: Continent, 10: City, 15: Streets, 20: Buildings"
    options:
      min: 0
      max: 20
      step: 0.25
  mapType:
    type: select
    options:
      values:
        - roadmap
        - satellite
        # - hybrid
        # - terrain
  # marker:
  #   type: switch
  #   comment: Show a marker pin at the center of the map
  height:
    type: number
    comment: Map height, in percentage of browser window height (vh).
    options:
      min: 0
      max: 100
  indent:
    type: switch
  # style:
  #   type: text
  #   comment: Use a legacy map style loaded from src/styles/<style>.map.json
  #   hidden: mapId
  # mapId:
  #   type: text
  #   label: Google Map ID
  #   comment: Override map style with Google Cloud Map Styling. Enables usage of Vector Maps via Google Cloud Console.

# Overrides any fields in the blueprint when viewing this component in the component browser

preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
# _inputs:
#   description:
#     type: markdown
