# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Image
  description: Display a single image.
  icon: image
  tags: ["image"]
  tabbed: true
  groups:
    - heading: Section
      inputs:
        - content
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
        - classes
  preview:
    gallery:
      image:
        - key: image
      text:
        - key: alt
    subtext:
      - key: title
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  image:
  title:
  description:
  alt:
  height: 50
  indent: true
  lightbox: true
  # height:
  color:
  content:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  classes:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  height:
    type: range
    options:
      step: 1
      max: 100
      min: 0
  columns:
    type: number
    comment: Set the number of columns. 0 puts all images in one row.
    options:
      step: 1
      min: 0
  indent:
    type: switch
  title:
    type: text
  alt:
    type: text
    comment: Alt text should describe the subject of an image as an accessability feature for screen-readers.
  description:
    type: markdown
  lightbox:
    type: checkbox
