spec:
  label: Section
  structures:
    - section

blueprint:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
  background_fit:
  background_blend:
  animation:
