# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content
  description: Rich text element.
  icon: edit_note
  tags: []
  place_groups_below: true
  groups:
    - heading: Section
      collapsed: true
      inputs:
        - classes
        - height
        - indent
        - align
        - color
        - background_color
        - background_image
        - background_video
        - background_align
        - background_opacity
        - background_fixed
  preview:
    image:
      - key: background_image
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  content:
  classes:
  height:
  indent:
  align:
  color:
  background_color:
  background_image:
  background_video:
  background_align:
  background_opacity:
  background_fixed:
