# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content
  description: Rich text element.
  icon: edit_note
  tags: []
  preview:
    image:
      - key: background_image
    metadata:
      - text:
          - key: classes
        icon: tag

# Defines the structure of this component, as well as the default values
blueprint:
  content:
  classes:
