# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content
  description: Rich text element.
  icon: edit_note
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
  style:

_inputs:
  content:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: src/styles/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true
  style:
    type: multiselect
    options:
      allow_create: true
      values:
        - no-indent
        - no-indent-top
        - no-indent-bottom
        - no-indent-left
        - no-indent-right

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
# _inputs:
#   description:
#     type: markdown
