# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Columns
  description: Layout content in columns.
  icon: view_column
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content_blocks: [bookshop:structure:content_blocks]
  collapse: true
  layout: [1]

_inputs:
  collapse:
    type: checkbox
    comment: Restrict to one column at small screen sizes
  layout:
    type: array
    comment: Set a fixed number of columns per row. The last row will be repeated in case of extra items.
  layout[*]:
    type: range
    options:
      min: 1
      step: 1
      max: 6

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
# Any extra CloudCannon inputs configuration to apply to the blueprint
# _inputs:
#   description:
#     type: markdown
